name = "Brassworks SMP Modpack"
author = "swzo, Pipo1660"
version = "2.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9500235f30e3f7770a9d0ef881ba4c62f0792bc606eef65836d9ccd48cd77e8a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"

[options]
acceptable-game-versions = ["1.21"]
