name = "Brassworks SMP Modpack"
author = "swzo, Pipo1660"
version = "2.6.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ceb55493c5a53052e1a4403d1d23afa2d5c12d5ad1504785183e625819b3137e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"

[options]
acceptable-game-versions = ["1.21"]
